// Demo content — fictional but plausible (MEXTAS website UI kit).
window.MX_DATA={
services:[
{slug:"corporativo",icon:"briefcase",title:"Derecho Corporativo",short:"Constitución de empresas, contratos, gobierno corporativo y cumplimiento normativo.",lead:"Protegemos y acompañamos la estructura jurídica de empresas en cada etapa de su crecimiento.",areas:["Constitución","Gobierno corporativo","Contratos","Reestructuras","Cumplimiento","Operaciones corporativas"],problems:["Pactos de socios que no anticipan salidas o conflictos","Órganos de gobierno sin actas ni facultades en orden","Crecimiento sin estructura societaria adecuada"],clients:"Empresas familiares, grupos empresariales, filiales de capital extranjero y fondos.",faq:[["¿Pueden actuar como área legal externa?","Sí. Operamos como departamento jurídico corporativo con un socio responsable y tiempos de respuesta pactados."],["¿Atienden sociedades constituidas en el extranjero?","Coordinamos con firmas corresponsales para estructuras con presencia en México y el exterior."]]},
{slug:"fusiones-adquisiciones",icon:"handshake",title:"Fusiones y Adquisiciones",short:"Acompañamiento legal en procesos de inversión, adquisiciones, reestructuras y operaciones estratégicas.",lead:"Conducimos operaciones de compra, venta e inversión con disciplina de proceso y lectura de negocio.",areas:["Due diligence","Cartas de intención","Contratos de compraventa","Joint ventures","Integración post-cierre","Inversión privada"],problems:["Contingencias ocultas en la empresa objetivo","Negociaciones sin estructura de garantías","Cierres que se retrasan por falta de coordinación"],clients:"Compradores estratégicos, fondos de capital privado, fundadores e inversionistas.",faq:[["¿Cuánto dura una auditoría legal?","Entre tres y seis semanas, según el alcance y la disponibilidad del cuarto de datos."]]},
{slug:"litigio-arbitraje",icon:"scale",title:"Litigio y Arbitraje",short:"Representación estratégica en disputas mercantiles, civiles y administrativas.",lead:"Defendemos la posición de nuestros clientes con estrategia procesal y visión de negocio.",areas:["Litigio mercantil","Arbitraje comercial","Litigio civil","Amparo","Medidas cautelares","Ejecución de laudos"],problems:["Incumplimientos contractuales relevantes","Disputas entre socios","Actos de autoridad que afectan la operación"],clients:"Empresas nacionales y extranjeras, directivos y accionistas.",faq:[["¿Evalúan alternativas antes de litigar?","Siempre. Cada asunto inicia con un análisis de riesgo, costo y vías de negociación."]]},
{slug:"propiedad-intelectual",icon:"lock-keyhole",title:"Propiedad Intelectual",short:"Protección de marcas, patentes, derechos de autor y activos intangibles.",lead:"Convertimos los activos intangibles en patrimonio protegido y defendible.",areas:["Registro de marcas","Patentes","Derechos de autor","Licenciamiento","Oposiciones","Vigilancia de marca"],problems:["Marcas sin registro en mercados clave","Uso no autorizado por terceros","Contratos de licencia ambiguos"],clients:"Marcas de consumo, empresas tecnológicas, creadores y franquiciantes.",faq:[["¿Registran marcas fuera de México?","Sí, vía Protocolo de Madrid y corresponsales en Estados Unidos, Europa y Latinoamérica."]]},
{slug:"laboral",icon:"users",title:"Derecho Laboral",short:"Relaciones laborales, contratación, auditorías y conflictos individuales o colectivos.",lead:"Ordenamos la relación con el talento para reducir contingencias y proteger la operación.",areas:["Contratos laborales","Auditoría laboral","Terminaciones","Relaciones sindicales","Reglamentos internos","Defensa ante tribunales"],problems:["Esquemas de contratación con riesgo","Terminaciones sin soporte documental"],clients:"Empresas medianas y grandes, áreas de recursos humanos.",faq:[]},
{slug:"inmobiliario",icon:"building-2",title:"Derecho Inmobiliario",short:"Adquisición, desarrollo, arrendamiento y financiamiento de activos inmobiliarios.",lead:"Estructuramos operaciones inmobiliarias con certeza jurídica desde la adquisición.",areas:["Compraventa","Arrendamiento comercial","Desarrollos","Fideicomisos","Uso de suelo","Due diligence inmobiliario"],problems:["Títulos con irregularidades","Contratos de arrendamiento desbalanceados"],clients:"Desarrolladores, family offices, inversionistas inmobiliarios.",faq:[]},
{slug:"fiscal",icon:"landmark",title:"Derecho Fiscal",short:"Planeación, cumplimiento y defensa en materia tributaria.",lead:"Acompañamos la toma de decisiones con una lectura fiscal rigurosa y defendible.",areas:["Planeación fiscal","Precios de transferencia","Auditorías SAT","Defensa fiscal","Comercio exterior"],problems:["Revisiones de la autoridad","Estructuras sin sustancia"],clients:"Empresas, grupos y personas de alto patrimonio.",faq:[]},
{slug:"contratos",icon:"file-signature",title:"Contratos",short:"Redacción, revisión y negociación de contratos comerciales complejos.",lead:"Contratos claros que anticipan el conflicto y protegen la relación comercial.",areas:["Suministro","Distribución","Servicios","Confidencialidad","Licencias"],problems:["Cláusulas de responsabilidad ambiguas"],clients:"Empresas de todos los sectores.",faq:[]},
{slug:"compliance",icon:"shield-check",title:"Compliance",short:"Programas de cumplimiento, anticorrupción e integridad corporativa.",lead:"Diseñamos programas de cumplimiento que funcionan en la operación diaria.",areas:["Anticorrupción","Códigos de ética","Investigaciones internas","Capacitación"],problems:["Riesgo reputacional por terceros"],clients:"Empresas reguladas y proveedores de gobierno.",faq:[]},
{slug:"proteccion-datos",icon:"database",title:"Protección de Datos",short:"Privacidad, avisos, transferencias y gestión de incidentes.",lead:"Tratamiento de datos personales conforme a la ley y a los estándares internacionales.",areas:["Avisos de privacidad","Transferencias","Incidentes","Auditoría"],problems:["Bases de datos sin consentimiento"],clients:"Plataformas digitales, retail, salud.",faq:[]},
{slug:"comercio-internacional",icon:"globe",title:"Comercio Internacional",short:"Operaciones transfronterizas, tratados comerciales y aduanas.",lead:"Acompañamos a empresas que compran, venden e invierten más allá de la frontera.",areas:["T-MEC","Aduanas","Contratos internacionales","Inversión extranjera"],problems:["Reglas de origen mal documentadas"],clients:"Exportadores, importadores y filiales extranjeras.",faq:[]},
{slug:"consultoria",icon:"compass",title:"Consultoría para Empresas",short:"Acompañamiento jurídico continuo para la dirección general.",lead:"Un socio legal en la mesa de decisiones de la dirección.",areas:["Consejo consultivo","Iguala corporativa","Evaluación de riesgos"],problems:["Decisiones sin análisis jurídico previo"],clients:"Direcciones generales y consejos de administración.",faq:[]}
],
cases:[
{slug:"reestructura-corporativa",image:"../../assets/img/caso-reestructura.png",title:"Reestructura Corporativa",summary:"Reestructuración estratégica de grupo empresarial.",client:"Grupo industrial familiar · 7 sociedades",location:"Monterrey, N.L.",areas:["Corporativo","Fiscal","Laboral"],challenge:"Un grupo con siete sociedades acumuladas en veinte años operaba sin una estructura clara de control, con duplicidad de funciones y riesgo fiscal por operaciones intercompañía.",strategy:"Proponer una sociedad controladora, depurar entidades inactivas y documentar la sucesión de la siguiente generación en un protocolo familiar.",intervention:"Fusiones y escisiones escalonadas, nuevos estatutos, pacto de accionistas y un consejo de administración con consejeros independientes.",result:"El grupo opera hoy con cuatro sociedades, un gobierno corporativo formal y un plan de sucesión aprobado por la asamblea.",timeline:[["Mes 1","Diagnóstico societario y fiscal"],["Mes 2–3","Diseño de la nueva estructura"],["Mes 4–7","Fusiones, escisiones y protocolización"],["Mes 8","Instalación del consejo"]]},
{slug:"contrato-internacional",image:"../../assets/img/caso-contrato.png",title:"Contrato Internacional",summary:"Negociación y elaboración de contratos de distribución.",client:"Fabricante europeo de equipo médico",location:"Ciudad de México · Milán",areas:["Contratos","Comercio Internacional","Propiedad Intelectual"],challenge:"El cliente entraba al mercado mexicano con un distribuidor exclusivo sin haber definido metas mínimas, uso de marca ni mecanismo de terminación.",strategy:"Negociar un contrato con exclusividad condicionada a desempeño y licencia de marca limitada.",intervention:"Redacción bilingüe, negociación en cuatro rondas y arbitraje con sede en la Ciudad de México.",result:"Contrato firmado en diez semanas, con indicadores de desempeño trimestrales y salida ordenada pactada.",timeline:[["Semana 1–2","Revisión de la propuesta del distribuidor"],["Semana 3–8","Negociación"],["Semana 9–10","Firma y registro de licencia"]]},
{slug:"litigio-comercial",image:"../../assets/img/caso-litigio.png",title:"Litigio Comercial",summary:"Representación exitosa en litigio mercantil complejo.",client:"Empresa de logística",location:"Guadalajara, Jal.",areas:["Litigio","Contratos"],challenge:"Un cliente estratégico suspendió pagos alegando incumplimientos de servicio no documentados, comprometiendo el flujo del cliente.",strategy:"Acreditar el cumplimiento con la bitácora operativa y solicitar medidas cautelares sobre cuentas por cobrar.",intervention:"Demanda en vía ordinaria mercantil, peritaje en logística y audiencias de conciliación.",result:"Sentencia favorable en primera instancia confirmada en apelación; recuperación del adeudo con intereses.",timeline:[["Mes 1","Análisis y medidas cautelares"],["Mes 2–9","Juicio y peritajes"],["Mes 10–14","Apelación y ejecución"]]},
{slug:"proteccion-de-marca",image:"../../assets/img/caso-marca.png",title:"Protección de Marca",summary:"Registro y defensa de marca a nivel internacional.",client:"Marca mexicana de bienes de consumo",location:"México · EE.UU. · España",areas:["Propiedad Intelectual","Litigio"],challenge:"Terceros registraron una marca casi idéntica en dos mercados de expansión antes de la llegada del cliente.",strategy:"Consolidar el portafolio vía Protocolo de Madrid y oponerse con evidencia de uso previo y notoriedad.",intervention:"Solicitudes en 9 clases, oposiciones y acuerdos de coexistencia donde convenía comercialmente.",result:"Portafolio registrado en los tres mercados y un protocolo de vigilancia trimestral.",timeline:[["Mes 1","Auditoría de portafolio"],["Mes 2–4","Solicitudes y oposiciones"],["Mes 5–12","Resolución y vigilancia"]]}
],
team:[
{slug:"alejandro-delgado",photo:"../../assets/img/equipo-alejandro-delgado.png",name:"Alejandro Delgado",role:"Socio Fundador",email:"adelgado@mextas.com.mx",specialty:["Derecho Corporativo","Fusiones y Adquisiciones","Gobierno Corporativo","Estrategia Empresarial"],bio:"Fundó MEXTAS tras dos décadas asesorando a grupos empresariales en México y Estados Unidos. Participa en consejos de administración y dirige las operaciones de adquisición de la firma.",experience:"22 años",languages:["Español","Inglés"],education:["Licenciatura en Derecho, Escuela Libre de Derecho","LL.M., Georgetown University"],cases:["Reestructura Corporativa"],publications:["Gobierno corporativo en la empresa familiar mexicana (2024)"]},
{slug:"mariana-santos",photo:"../../assets/img/equipo-mariana-santos.png",name:"Mariana Santos",role:"Directora Legal",email:"msantos@mextas.com.mx",specialty:["Contratos","Comercio Internacional","Compliance"],bio:"Coordina la práctica transaccional y los programas de cumplimiento. Negocia contratos internacionales para clientes de Europa y Norteamérica.",experience:"15 años",languages:["Español","Inglés","Italiano"],education:["Licenciatura en Derecho, ITAM","Maestría en Derecho Mercantil Internacional, Universidad de Bolonia"],cases:["Contrato Internacional"],publications:["Cláusulas de salida en contratos de distribución (2025)"]},
{slug:"ricardo-mendoza",photo:"../../assets/img/equipo-ricardo-mendoza.png",name:"Ricardo Mendoza",role:"Socio de Litigio",email:"rmendoza@mextas.com.mx",specialty:["Litigio Mercantil","Arbitraje","Amparo"],bio:"Dirige la práctica contenciosa. Ha representado a empresas en juicios mercantiles, arbitrajes comerciales y amparos de alto impacto.",experience:"18 años",languages:["Español","Inglés"],education:["Licenciatura en Derecho, UNAM","Especialidad en Derecho Procesal, Universidad Panamericana"],cases:["Litigio Comercial"],publications:["Medidas cautelares en el juicio mercantil (2023)"]},
{slug:"daniela-flores",photo:"../../assets/img/equipo-daniela-flores.png",name:"Daniela Flores",role:"Asociada Senior",email:"dflores@mextas.com.mx",specialty:["Propiedad Intelectual","Protección de Datos"],bio:"Gestiona el portafolio de marcas y la práctica de privacidad. Asesora a empresas de consumo y tecnología en su expansión internacional.",experience:"9 años",languages:["Español","Inglés","Francés"],education:["Licenciatura en Derecho, Universidad Iberoamericana","Diplomado en Propiedad Intelectual, OMPI"],cases:["Protección de Marca"],publications:["Activos intangibles: una guía para directores (2025)"]}
],
articles:[
{slug:"contrato-comercial-solido",cat:"Contratos",date:"12 sep 2026",read:"6 min",image:"../../assets/img/sala-de-juntas.png",title:"¿Qué debe contener un contrato comercial sólido?",excerpt:"Objeto, precio y plazo son solo el inicio. Las cláusulas que protegen a una empresa son las que anticipan el desacuerdo.",body:["Un contrato comercial no es un trámite: es el mapa de cómo dos partes resolverán lo que salga mal.","Además de las obligaciones principales, debe definir con precisión la responsabilidad, los límites de indemnización, las causales de terminación y el mecanismo de solución de controversias.","Recomendamos revisar cada contrato relevante al menos una vez al año o ante cualquier cambio en la operación."]},
{slug:"riesgos-antes-de-crecer",cat:"Corporativo",date:"28 ago 2026",read:"8 min",image:"../../assets/img/caso-reestructura.png",title:"Cinco riesgos jurídicos que una empresa debe identificar antes de crecer.",excerpt:"Estructura societaria, contratos, laboral, fiscal y propiedad intelectual: dónde suelen aparecer las contingencias.",body:["El crecimiento amplifica lo que ya existe, incluidas las debilidades jurídicas.","Antes de levantar capital o abrir mercados, conviene una auditoría legal que ordene la estructura, documente las relaciones laborales y asegure la titularidad de marcas."]},
{slug:"activos-intangibles",cat:"Propiedad Intelectual",date:"9 ago 2026",read:"5 min",image:"../../assets/img/caso-marca.png",title:"Propiedad intelectual: cómo proteger los activos intangibles de una empresa.",excerpt:"La marca, el software y el know-how suelen valer más que los activos físicos. Protegerlos exige método.",body:["Registrar la marca en cada mercado relevante antes de entrar es la medida más rentable.","Los contratos con empleados y proveedores deben prever la cesión de derechos sobre lo que desarrollan."]},
{slug:"fusiones-aspectos-esenciales",cat:"Fusiones y Adquisiciones",date:"21 jul 2026",read:"7 min",image:"../../assets/img/caso-contrato.png",title:"Fusiones y adquisiciones: aspectos legales esenciales.",excerpt:"De la carta de intención al cierre: las etapas, los documentos y las decisiones que determinan el éxito de una operación.",body:["Toda operación inicia con una carta de intención que fija exclusividad y confidencialidad.","La auditoría legal define el precio y las garantías; el contrato de compraventa distribuye los riesgos identificados."]}
]};
